from __future__ import annotations

RULES = (
    "rule-001: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-002: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-003: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-004: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-005: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-006: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-007: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-008: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-009: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-010: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-011: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-012: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-013: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-014: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-015: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-016: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-017: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-018: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-019: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-020: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-021: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-022: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-023: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-024: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-025: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-026: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-027: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-028: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-029: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-030: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-031: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-032: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-033: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-034: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-035: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-036: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-037: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-038: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-039: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-040: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-041: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-042: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-043: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-044: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-045: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-046: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-047: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-048: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-049: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-050: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-051: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-052: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-053: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-054: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-055: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-056: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-057: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-058: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-059: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-060: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-061: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-062: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-063: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-064: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-065: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-066: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-067: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-068: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-069: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-070: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-071: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-072: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-073: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-074: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-075: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-076: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-077: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-078: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-079: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-080: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-081: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-082: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-083: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-084: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-085: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-086: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-087: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-088: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-089: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-090: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-091: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-092: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-093: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-094: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-095: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-096: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-097: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-098: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-099: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-100: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-101: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-102: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-103: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-104: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-105: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-106: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-107: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-108: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-109: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-110: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-111: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
    "rule-112: preserve the audit decision, owner, timestamp, and next action when this record is summarized",
)


def rule_count() -> int:
    return len(RULES)


def find_rule(prefix: str) -> str | None:
    return next((rule for rule in RULES if rule.startswith(prefix)), None)
